config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :songs
  resources :couples
  resources :dances
  resources :artists
  resources :leaders,   controller: 'artists', type: "leader"
  resources :followers, controller: 'artists', type: "follower"

  get 'welcome/index'

  match 'dances/:video/:couple', to: 'dances#new', as: 'dance_add', via: [:get]

  root 'welcome#index'

end

app/models/couple.rb
class Couple < ActiveRecord::Base
  belongs_to :leader
  belongs_to :follower

  has_many :dances

  def name
    follower.name + " & ".html_safe + leader.name
  end

=begin
  def follower
    Artist.find(follower_id)
  end

  def leader
    Artist.find(leader_id)
  end
=end

end

app/controllers/admin/couples_controller.rb
module Admin
  class CouplesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Couple.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Couple.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/couples_controller.rb
class CouplesController < ApplicationController
  before_action :set_couple, only: [:show, :edit, :update, :destroy]

  # GET /couples
  # GET /couples.json
  def index
    @couples = Couple.all
  end

  # GET /couples/1
  # GET /couples/1.json
  def show
    @dances = @couple.dances

    @search = Google::Search::Video.new do |search|
      search.query = @couple.name
      search.size = :large
    end

    @uris = Array.new
    @search.response.each do |res|
      yt_id = YoutubeID.from(res.uri)
      @uris.push(yt_id) unless Dance.find_by_youtube_id(yt_id).present?
    end


    @results = @uris.count > 1 ? @search.response : @search.next.response

  end

  # GET /couples/new
  def new
    @couple = Couple.new
  end

  # GET /couples/1/edit
  def edit
  end

  # POST /couples
  # POST /couples.json
  def create
    @couple = Couple.new(couple_params)

    respond_to do |format|
      if @couple.save
        format.html { redirect_to @couple, notice: 'Couple was successfully created.' }
        format.json { render :show, status: :created, location: @couple }
      else
        format.html { render :new }
        format.json { render json: @couple.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /couples/1
  # PATCH/PUT /couples/1.json
  def update
    @couple.artists << Artist.find(params[:couple][:leader_id])
    @couple.artists << Artist.find(params[:couple][:follower_id])

    respond_to do |format|
      if @couple.update(couple_params)
        format.html { redirect_to @couple, notice: 'Couple was successfully updated.' }
        format.json { render :show, status: :ok, location: @couple }
      else
        format.html { render :edit }
        format.json { render json: @couple.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /couples/1
  # DELETE /couples/1.json
  def destroy
    @couple.destroy
    respond_to do |format|
      format.html { redirect_to couples_url, notice: 'Couple was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_couple
      @couple = Couple.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def couple_params
      params.require(:couple).permit(:start, :end, :leader_id, :follower_id)
    end
end

app/helpers/couples_helper.rb
module CouplesHelper
end

app/views/couples/_form.html.haml
= simple_form_for @couple do |f|
  - if @couple.errors.any?
    #error_explanation
      %h2= "#{pluralize(@couple.errors.count, "error")} prohibited this couple from being saved:"
      %ul
        - @couple.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :leader_id, collection: Leader.all.sort_by { |leader | leader.first_name  }, label_method: :name, prompt: true
  .field
    = f.input :follower_id, collection: Follower.all.sort_by { |fol | fol.first_name  }, label_method: :name, prompt: true
  .field
    = f.input :link, label: "Link to webpage"
  .field
    = f.input :start, prompt: true
  .field
    = f.input :end, prompt: true
  .actions
    = f.button :submit

app/views/couples/edit.html.haml
%h1 Editing couple

= render 'form'

= link_to 'Show', @couple
\|
= link_to 'Back', couples_path

app/views/couples/index.html.haml
%h1 Listing couples

%table
  %thead
    %tr
      %th Follower
      %th Leader
      %th Known dances
      %th Start
      %th End
      %th
      %th
      %th

  %tbody
    - @couples.each do |couple|
      %tr
        %td= link_to couple.follower.name, artist_path(couple.follower_id)
        %td= link_to couple.leader.name, artist_path(couple.leader_id)
        %td= couple.dances.count
        %td= couple.start
        %td= couple.end
        %td= link_to 'Show', couple
        %td= link_to 'Edit', edit_couple_path(couple)
        %td= link_to 'Destroy', couple, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Couple', new_couple_path

app/views/couples/new.html.haml
%h1 New couple

= render 'form'

= link_to 'Back', couples_path

app/views/couples/show.html.haml
.medium-12.columns
  %nav{"aria-label" => "You are here:", :role => "navigation"}
  %ul.breadcrumbs
    %li
      %a{:href => welcome_index_url} Home
    %li
      %a{:href => dances_url} Dances
    %li
      %span.show-for-sr Current:
      = "ID=" +  @couple.id.to_s
  %ul.breadcrumbs
    %li
      = link_to 'Edit', edit_couple_path(@couple)
    %li
      = link_to 'Back', couples_path
    %li
      = link_to 'Add new', new_dance_path

.medium-8.columns
  %p#notice= notice

  %h3
    = @couple.name

  %h4
    TMDD Dances
  %table
    %tbody
      %thead
        %td= "Date"
        %td= "Video Date"
        %td= "Location"
        %td= "Youtube ID"
        %td
      - @dances.each do |row|
        %tr
          %td= row.date
          %td= row.video_date
          %td= row.location
          %td= row.youtube_id
          %td= link_to "view", dance_path(row)


  %h4
    More Videos
    %p
      also on google
      =link_to "google", "https://www.google.lu/?q=#{sanitize(@couple.name)}#"

  - @results.items.each do |response|
    - yt_id = YoutubeID.from(response.uri)
    - if Dance.find_by_youtube_id(yt_id)
    - else
      %p
        =response.title.html_safe
        =link_to "add to TMDD", dance_add_path(video: YoutubeID.from(response.uri), couple: @couple.id)
        =Yt::Video.new(url: response.uri).embed_html.html_safe

.medium-3.columns{"data-sticky-container" => ""}
  .sticky{"data-anchor" => "content", "data-sticky" => ""}
    %h4
      Couple Metadata
    %p
      %b Started dancing
      = @couple.start
    %p
      %b Ended dancing
      = @couple.end