config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :songs
  resources :couples
  resources :dances
  resources :artists
  resources :leaders,   controller: 'artists', type: "leader"
  resources :followers, controller: 'artists', type: "follower"

  get 'welcome/index'

  match 'dances/:video/:couple', to: 'dances#new', as: 'dance_add', via: [:get]

  root 'welcome#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :couples

  def name
    first_name + " " + last_name
  end
end

app/controllers/admin/artists_controller.rb
module Admin
  class ArtistsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Artist.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Artist.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params_create)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params_update)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params_update
      params.require(params[:type].to_sym).permit(   :first_name, :last_name, :sex)
    end
    def artist_params_create
      params.require(:artist).permit(   :first_name, :last_name, :sex, :type)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.haml
= simple_form_for @artist do |f|
  - if @artist.errors.any?
    #error_explanation
      %h2= "#{pluralize(@artist.errors.count, "error")} prohibited this artist from being saved:"
      %ul
        - @artist.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :first_name
  .field
    = f.input :last_name
  .field
    = f.input :sex, collection: [:male, :female], as: :radio_buttons
  .field
    = f.input :type, collection: ["Leader", "Follower"], as: :radio_buttons

  .actions
    = f.button :submit

app/views/artists/edit.html.haml
%h1 Editing artist

= render 'form'

= link_to 'Show', @artist
\|
= link_to 'Back', artists_path

app/views/artists/index.html.haml
%h1 List of artists
= link_to 'New Artist', new_artist_path, :class => 'small button'

%table
  %thead
    %tr
      %th First Name
      %th Last Name
      %th Gender
      %th Role
      %th
      %th

  %tbody
    - @artists.each do |artist|
      %tr
        %td= artist.first_name
        %td= artist.last_name
        %td= artist.sex
        %td= artist.type
        %td= link_to 'Edit', edit_artist_path(artist), :class => 'tiny button'
        %td= link_to 'Destroy', artist_path(artist), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'tiny alert button'

%br

app/views/artists/new.html.haml
%h1 New artist

= render 'form'

= link_to 'Back', artists_path

app/views/artists/show.html.haml
%p#notice= notice

%h2
  = @artist.first_name + " " + @artist.last_name
%p
  %b Sex:
  = @artist.sex
%p
  %b Role:
  = @artist.type

%h3
  Couples
%table
  %tbody
    %thead
      %td= "Follower"
      %td= "Leader"
      %td= "Dances"
    - @artist.couples.each do |row|
      %tr
        %td= row.follower.name
        %td= row.leader.name
        %td= link_to (row.dances.count.to_s + " known"), couple_path(row.id)




= link_to 'Edit', edit_artist_path(@artist)
\|
= link_to 'Back', artists_path(@artist)