config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :songs
  resources :couples
  resources :dances
  resources :artists
  resources :leaders,   controller: 'artists', type: "leader"
  resources :followers, controller: 'artists', type: "follower"

  get 'welcome/index'

  match 'dances/:video/:couple', to: 'dances#new', as: 'dance_add', via: [:get]

  root 'welcome#index'

end

app/models/dance.rb
class Dance < ActiveRecord::Base
  belongs_to :couple
  belongs_to :song

  def youtube_id=(value)
    write_attribute(:youtube_id , value)
    #video_date = Yt::Video.new(id: value ).published_at
  end
end

app/controllers/dances_controller.rb
class DancesController < ApplicationController
  before_action :set_dance, only: [:show, :edit, :update, :destroy]
  respond_to :html

  # GET /dances
  # GET /dances.json
  def index
    @dances = Dance.all
  end

  # GET /dances/1
  # GET /dances/1.json
  def show
    if @dance.youtube_id
      @video = Yt::Video.new id:  @dance.youtube_id
    else
      @video = Yt::Video.new url:  @dance.link
    end

  end

  # GET /dances/new
  def new
    form Dance::Create

    # @dance = Dance.new
    # @dance.link = "https://www.youtube.com/watch?v=#{params[:video]}" rescue ""
    # @dance.youtube_id = params[:video] rescue nil
    # @dance.couple = Couple.find(params[:couple]) rescue nil
  end

  # GET /dances/1/edit
  def edit
      form Dance::Update
      render action: :new
  end

  # POST /dances
  # POST /dances.json
  def create
    #this is the new trailblazer code
    run Dance::Create do |op|
      return redirect_to op.model
    end
    render action: :new

    # @dance = Dance.new(dance_params)
    # @dance.youtube_id = YoutubeID.from(@dance.link)
    #
    # respond_to do |format|
    #   if @dance.save
    #     format.html { redirect_to @dance, notice: 'Dance was successfully created.' }
    #     format.json { render :show, status: :created, location: @dance }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @dance.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /dances/1
  # PATCH/PUT /dances/1.json
  def update

    @dance.youtube_id = YoutubeID.from(params[:dance][:link])
    @video = Yt::Video.new url: params[:dance][:link]
    @dance.video_date = @video.published_at

    respond_to do |format|
      if @dance.update(dance_params)
        format.html { redirect_to @dance, notice: 'Dance was successfully updated.' }
        format.json { render :show, status: :ok, location: @dance }
      else
        format.html { render :edit }
        format.json { render json: @dance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dances/1
  # DELETE /dances/1.json
  def destroy
    @dance.destroy
    respond_to do |format|
      format.html { redirect_to dances_url, notice: 'Dance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dance
      @dance = Dance.find(params[:id])
    end

    #Never trust parameters from the scary internet, only allow the white list through.
    def dance_params
       params.require(:dance).permit(:date, :location, :link, :couple_id, :song_id, :video_date)
     end

    def update_youtube_id
      self.youtube_id = YoutubeID.from(self.link)
    end
end

app/helpers/dances_helper.rb
module DancesHelper
end

app/views/dances/_form.html.haml
= simple_form_for @form do |f|
  - if @form.errors.any?
    #error_explanation
      %h2= "#{pluralize(@form.errors.count, "error")} prohibited this dance from being saved:"
      %ul
        - @form.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :couple_id, collection: Couple.all, label_method: :name, prompt: true
  .field
    = f.input :date, prompt: true
  .field
    = f.input :location
  .field
    = f.input :link
  .field
    = f.input :song_id, collection: Song.all, label_method: :to_s, prompt: true
  .actions
    = f.button :submit

app/views/dances/edit.html.haml
%h1 Editing performance

= render 'form'

= link_to 'Show', @dance
\|
= link_to 'Back', dances_path

app/views/dances/index.html.haml
%h1 Listing dances

%table
  %thead
    %tr
      %th Date
      %th Video Date
      %th Couple
      %th Music
      %th Location
      %th Link
      %th
      %th
      %th

  %tbody
    - @dances.each do |dance|
      %tr
        %td= dance.date
        %td= dance.video_date
        %td= link_to dance.couple.name, couple_path(dance.couple)
        %td= link_to dance.song.to_s, songs_path(dance.song)
        %td= dance.location
        %td= link_to 'link', dance.link
        %td= link_to 'Show', dance
        %td= link_to 'Edit', edit_dance_path(dance)
        %td= link_to 'Destroy', dance, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Dance', new_dance_path

app/views/dances/new.html.haml
%h1 New dance

= render 'form'

= link_to 'Back', dances_path

app/views/dances/show.html.haml
.medium-12.columns
  %nav{"aria-label" => "You are here:", :role => "navigation"}
  %ul.breadcrumbs
    %li
      %a{:href => welcome_index_url} Home
    %li
      %a{:href => dances_url} Dances
    %li
      %span.show-for-sr Current:
      = "ID=" +  @dance.id.to_s
  %ul.breadcrumbs
    %li
      = link_to 'Edit', edit_dance_path(@dance)
    %li
      = link_to 'Add new', new_dance_path

.medium-8.columns

  %p#notice= notice

  %h3
    = link_to @dance.couple.name, couple_path(@dance.couple)
  %h4
    = @dance.location + ", " + @dance.video_date.stamp("15. Oct 2016").to_s rescue ""
  %p
    %b Music:
    = @dance.song.to_s
  %p
    = @video.embed_html.html_safe
  = link_to 'Edit', edit_dance_path(@dance)
  \|
  = link_to 'Back', dances_path

.medium-3.columns{"data-sticky-container" => ""}
  .sticky{"data-anchor" => "content", "data-sticky" => ""}
    %h4
      Youtube Metadata
    %p
      %b Video ID:
      = link_to @dance.youtube_id, @dance.link
    %p
      %b Published:
      = @video.published_at.stamp("15. Oct 2016")
    %p
      %b= @video.title
      %p= @video.description