config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :songs
  resources :couples
  resources :dances
  resources :artists
  resources :leaders,   controller: 'artists', type: "leader"
  resources :followers, controller: 'artists', type: "follower"

  get 'welcome/index'

  match 'dances/:video/:couple', to: 'dances#new', as: 'dance_add', via: [:get]

  root 'welcome#index'

end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :dances

  def to_s
    "''" + title.titleize + "'' by " + orchestra
  end

end

app/controllers/admin/songs_controller.rb
module Admin
  class SongsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Song.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Song.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @dances = @song.dances

    @search = Google::Search::Video.new do |search|
      search.query = @song.to_s
      search.size = :small
    end

    @results = @search.response

  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :orchestra)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.haml
= simple_form_for(@song) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :orchestra

  .form-actions
    = f.button :submit

app/views/songs/edit.html.haml
%h1 Editing music

= render 'form'

= link_to 'Show', @song
\|
= link_to 'Back', songs_path

app/views/songs/index.html.haml
%h1 Listing songs

%table
  %thead
    %tr
      %th Title
      %th Orchestra
      %th # of dances
      %th
      %th
      %th

  %tbody
    - @songs.each do |song|
      %tr
        %td= song.title.titleize
        %td= song.orchestra.titleize
        %td= song.dances.count
        %td= link_to 'Show', song
        %td= link_to 'Edit', edit_song_path(song)
        %td= link_to 'Destroy', song, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Song', new_song_path

app/views/songs/new.html.haml
%h1 New music

= render 'form'

= link_to 'Back', songs_path

app/views/songs/show.html.haml
.medium-12.columns
  %nav{"aria-label" => "You are here:", :role => "navigation"}
  %ul.breadcrumbs
    %li
      %a{:href => welcome_index_url} Home
    %li
      %a{:href => songs_url} Songs
    %li
      %span.show-for-sr Current:
      = "ID=" +  @song.id.to_s
  %ul.breadcrumbs
    %li
      = link_to 'Edit', edit_song_path(@song)
    %li
      = link_to 'Back', songs_url
    %li
      = link_to 'Add new', new_song_path

.medium-8.columns
  %p#notice= notice

  %h2
    = @song.to_s

  %h4
    Known Dances
  %table
    %tbody
      %thead
        %td= "Couple"
        %td= "Location"
        %td= "Date"
        %td= "Link"
      - @dances.each do |row|
        %tr
          %td= row.couple.name
          %td= row.location
          %td= row.video_date.nil? ? row.date : row.video_date
          %td= link_to "link", dance_path(row)


  %h4
    More about this song

  - @results.items.each do |response|
    %p
      =response.title.html_safe
      =link_to "add to TMDD", new_dance_path
      =Yt::Video.new(url: response.uri).embed_html.html_safe

.medium-3.columns{"data-sticky-container" => ""}
  .sticky{"data-anchor" => "content", "data-sticky" => ""}
    %h4
      Song Metadata
    %p
      %b Title:
      = @song.title.titleize
    %p
      %b Orchestra:
      = @song.orchestra.titleize
    %p
      %b Learn more on the web:
      %ul
        %li= link_to "tango.info", "https://tango.info/?q=#{@song.title}"
        %li= link_to "tango-dj.at", "http://www.tango-dj.at/database/index.htm?titlesearch=#{@song.title}"